# This is a basic workflow to help you get started with Actions

name: clang-format

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.cpp_exercises/day2/date'
        extensions: 'h,cpp'
        clangFormatVersion: 11
        style: chromium
          
